// src/features/api/products/productSlice.js

import { createSlice } from "@reduxjs/toolkit";

// Define the initial state for the product slice
const initialState = {
  products: [], // Initialize as an empty array to store product objects
  // You can add other state properties here if needed (e.g., loading, error)
};

/**
 * Product Slice
 * Manages the state of products within the application.
 */
const productSlice = createSlice({
  name: "product",
  initialState,
  reducers: {
    /**
     * Sets the products array in the state.
     * @param {Object} state - The current state of the product slice.
     * @param {Object} action - The action dispatched.
     * @param {Array} action.payload - An array of product objects to set.
     */
    setProducts: (state, action) => {
      if (Array.isArray(action.payload)) {
        state.products = action.payload;
      } else {
        console.error(
          "setProducts action payload should be an array. Received:",
          action.payload
        );
      }
    },

    /**
     * Adds a new product to the products array.
     * @param {Object} state - The current state of the product slice.
     * @param {Object} action - The action dispatched.
     * @param {Object} action.payload - The product object to add.
     */
    addProduct: (state, action) => {
      const newProduct = action.payload;
      if (newProduct && newProduct._id) {
        state.products.push(newProduct);
      } else {
        console.error(
          "addProduct action payload must be a product object with an '_id' field. Received:",
          action.payload
        );
      }
    },

    /**
     * Updates an existing product in the products array.
     * @param {Object} state - The current state of the product slice.
     * @param {Object} action - The action dispatched.
     * @param {Object} action.payload - An object containing the id and updatedProduct.
     * @param {string} action.payload.id - The _id of the product to update.
     * @param {Object} action.payload.updatedProduct - The updated product data.
     */
    updateProduct: (state, action) => {
      const { id, updatedProduct } = action.payload;

      if (!id || !updatedProduct) {
        console.error(
          "updateProduct action payload must contain 'id' and 'updatedProduct'. Received:",
          action.payload
        );
        return;
      }

      // Find the index of the product to update using _id
      const productIndex = state.products.findIndex(
        (product) => product._id === id
      );

      if (productIndex !== -1) {
        // Merge the existing product with the updated fields
        state.products[productIndex] = {
          ...state.products[productIndex],
          ...updatedProduct,
        };
      } else {
        console.warn(
          `updateProduct: No product found with _id '${id}'. Update skipped.`
        );
      }
    },

    /**
     * Deletes a product from the products array.
     * @param {Object} state - The current state of the product slice.
     * @param {Object} action - The action dispatched.
     * @param {string} action.payload - The _id of the product to delete.
     */
    deleteProduct: (state, action) => {
      const id = action.payload;

      if (!id) {
        console.error(
          "deleteProduct action payload must be the '_id' of the product to delete. Received:",
          action.payload
        );
        return;
      }

      const initialLength = state.products.length;
      state.products = state.products.filter((product) => product._id !== id);

      if (state.products.length === initialLength) {
        console.warn(
          `deleteProduct: No product found with _id '${id}'. Deletion skipped.`
        );
      }
    },
  },
});

// Export the action creators generated by createSlice
export const { setProducts, addProduct, updateProduct, deleteProduct } =
  productSlice.actions;

// Export the reducer to be included in the store
export default productSlice.reducer;
